server:
  port: 8081
spring:
  application:
    name: service1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    register-with-eureka: false
    fetch-registry: false