spring:
  application:
    name: service1

server:
  port: 8081
  address: 0.0.0.0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true