spring:
  application:
    name: persons-service # Service registers under this name
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:personsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    maximum-pool-size: 5
    connection-test-query: "SELECT 1"
    pool-name: cemsPool
    connection-timeout: 60000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
# HTTP Server
server:
  port: 4001   # HTTP (Tomcat) port
  address: 0.0.0.0

# Discovery Server Access
#TODO here you add configurations for eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    fetchRegistry: true

info:
  app:
    name: persons-server
    description: Spring Cloud Application Managing Person Instances
    version: 1.0-SNAPSHOT

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.apress.cems: DEBUG